package ylab.alignment.simple

import org.scalatest.{FlatSpec, Matchers}
import ylab.alignment.logic.simple.LocalAlignment
import ylab.alignment.{Horizontal, Vertical}

/**
 * User: pavel
 * Date: 12.10.15
 * Time: 16:40
 */
class LocalAlignmentTest extends FlatSpec with Matchers {
  private val dummySub = (c : Char, d : Char) => if (c == d) 1 else -1

  "Local alignment" should "align equal strings" in {
    val la = new LocalAlignment[Char](10, 10, dummySub, -1)
    val s = "Hello!"

    la.push(s)(Horizontal)
    la.push(s)(Vertical)

    val result = la.traceback()
    result.score should be (s.length)
    result.horizontal should contain theSameElementsInOrderAs result.vertical
  }

  it should "align with mismatches" in {
    val la = new LocalAlignment[Char](10, 10, dummySub, -1)

    la.push("AACGT")(Horizontal)
    la.push("AAGGT")(Vertical)

    val result = la.traceback()
    result.score should be (3)
    result.horizontal.size should be (5)
    result.vertical.size should be (5)
  }

  it should "align with indels" in {
    val la = new LocalAlignment[Char](10, 10, dummySub, -1)

    la.push("ACGT")(Horizontal)
    la.push("AGT")(Vertical)

    val result = la.traceback()

    result.score should be (2)
    result.horizontal.size should be (2)
    result.vertical.size should be (2)
    result.vertical should be (result.horizontal)
  }

  it should "work very fast with long sequences" in {
    val ga = new LocalAlignment[Char](1000, 1000, dummySub, -1)

    val a = "GACGGTTAGGTTCGCACAAGGCGTTTTTGCTATCGGCGTATCGGTCCAGCGAGACGGACGCTTGCTGCCGAGCCCTGACGAACTAAACACTAGAACGAGCAGACAGACAAACTTGTCATTTAGGGGCATAAGCATGCAGGGCCGTGTGCAAAATGCTCTTCTTCACCGGGCCGCTGCCGCCCGAGATCGACTGACTTGGGCCGGGTAAGCGGCGCTGTATGTTAAGTGGCGAGAGATCCCGGAGTTTACCCCTGAGCTCTTTTTGTACGGTTCCAAAAATTCCCTTCTCCGGGTTCGTCGTCACCGTCGCTATCCGTGGTTTTCGTACTAGTACGGGTATCCCCGCTTGACCGCATGGCTAAGAGTTCCGCGGTTTACGTATGTTTGAAATTTAATTGTTTATAAGGCGTAACCTAGAAAGGTTGAATTCCCTGCCCGTGTTGGTATACCGTTACCGAAAATCTATGTCGCCGCGAACGTAGTAAGTCATGCTCCTGAGTCCTTTTGGACAACTATAGTGTGGATTGTACTGTGATTCTTTAGACATTTACCATACACGGCCAGTTACCGTGAATACGAATACATCAAGTGCAGATGACGGAAATAAGCGAGAGTTTTCTTTATGCTTCGGCCAGCTGTAAATTTGTTTTCCTATATGATCCCCGAGATAGTCGGCTTGAACGAACTGGTGCCATGTGACACTCTGGCACCGATCGGTGTTGGGCGCAGCGAATTTTTTCCTTACAGATATAGCGAGCCACACGGTTGTTACGGAGTCATAGTCCCAGCCCCGGACCGTAAGTGTCTTAAAGCGTCCTGATTCGCACTTCGATTGTTGAAATGGGACGATCCGTCCCTTCAGCGCAACCGACATGCAACGGCCC"
    val b = "GACGGTCACGATTCACATCGCGTCTTATTGAGCGTTAGCGTATTCGTTCCAACGCGTTACGACGCCGTTAGCATAGCCGTAGCCCTGACACACTAAAAAGTTACAACAATCAGACGACTTAACCTATCATTTAGGCCAGAAAGTGTGAGGCCTGATTGTCAGAAAGCTTCTCTCACCGGGCCGCTCCGCCGGAGGTCACGTATGGGCGGGCTAACCGGCGCTTTTGTTAAAGCTTCAGCATCCCGAATTGTTACCCCGGTCGCTCTTTTTGTACGGGTTCCAAAACCTATGTTCGAGTTTGCTCGTCACGGGCCTATCGTGGTTTCTGTACGAGGTAAGTGCATTCCCGCGTTGACGGCTCGGGAAGAGTTCCAGCTGGATTTACGCCTGTCTGAATCTATAGTGTTTATGATACTAAGCACTAGCATAAGGTTGAATTTCCCCTTGCCCCGTGGTTGTGTACCGTTGCCGTAGAATTCAATGCGAATCGCGAACCTGTATAGGTTCATGCTCTGAATATCCCTGTTGGACGAATTATTTGTGTGGATTGTAATGTTGATCCTCGAGTATACATTTACCCATACAGCGCTCATTACTCGTTATGCAAATCATCAAGAAGCTGATGGGAACTGAAGGAGAGATCTCCTTGCTGTACGCCAGCTGTACAACTATTATTGCTTACATGAAACCCTTGATAGTCAGTTGACCCGAACTGGTGCCATGTATACCTTAGCCCGGCCGGGTTGGGGCGCACGCGAATTTTTCTTACCTGCGATCAGCAAACCCACATGTCCTCACGATCAGTAGGCCCAGCCCCGCGACCGTAGCGTCTATAGCGTCGTGATCCGCACTTTGTTGTCTAAGACCCTGGGCAGGTTCGTGCCCTTGCGCACTACATGCACGGCCC"

    var sum = 0
    var tm = System.currentTimeMillis()
    (0 until 50).foreach {
      case i =>
        ga.push(a)(Horizontal)
        ga.push(b)(Vertical)

        val result = ga.traceback()

        ga.pop(a.length)(Horizontal)
        ga.pop(b.length)(Vertical)

        sum += result.score
    }
    tm = System.currentTimeMillis() - tm
    println(s"Time spent: ${1.0 * tm / 1000}s")
  }
}
